"""Added pinned field for posts

Revision ID: 5a6e711634c7
Revises: 16f1b325c4c8
Create Date: 2026-08-31 21:03:36.438530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6e711634c7'
down_revision: Union[str, Sequence[str], None] = '16f1b325c4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'pinned')
    # ### end Alembic commands ###
